### ISSUE TITLE
qasrl_parser NotImplementedException()

### ISSUE THREAD

**Issue by mengf1** [nafitzgerald/nrl-qasrl#10]
Run __Evaluating on the dense dev set__
```
$ env CUDA_VISIBLE_DEVICES=1 python -m allennlp.run evaluate model.tar.gz --evaluation-data-file data/qasrl-v2/dense/dev.jsonl.gz --cuda-device 0 --include-package nrl --overrides '{"dataset_reader": {"question_sources": "turk", "min_answers": 6, "min_valid_answers": 5}}'
```
Then have error as following

```
2018-07-17 22:01:28,131 - INFO - allennlp.commands.evaluate - Iterating over dataset
  0%|                                                                                                                                                                                      | 0/70 [00:00<?, ?it/s]Traceback (most recent call last):
  File "/usr/local/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/local/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/data2/env/py3-test2/lib/python3.6/site-packages/allennlp/run.py", line 18, in <module>
    main(prog="allennlp")
  File "/data2/env/py3-test2/lib/python3.6/site-packages/allennlp/commands/__init__.py", line 70, in main
    args.func(args)
  File "/data2/env/py3-test2/lib/python3.6/site-packages/allennlp/commands/evaluate.py", line 134, in evaluate_from_args
    metrics = evaluate(model, instances, iterator, args.cuda_device)
  File "/data2/env/py3-test2/lib/python3.6/site-packages/allennlp/commands/evaluate.py", line 97, in evaluate
    model(**batch)
  File "/data2/env/py3-test2/lib/python3.6/site-packages/torch/nn/modules/module.py", line 491, in __call__
    result = self.forward(*input, **kwargs)
  File "/data2/Workspace/nrl-qasrl/nrl/models/qasrl_parser.py", line 30, in forward
    raise NotImplementedException()
NameError: name 'NotImplementedException' is not defined
```

**Comment by mengf1** [comment]
Solved. Can not use a combined model here.
