### ISSUE TITLE
inconsistent checkpoint and model tensor sizes

### ISSUE THREAD

**Issue by lelayf** [nafitzgerald/nrl-qasrl#4]
**Environment**

- Python 3.6
- allennlp 0.5.1
- torch 0.4.0

**Execution**
```
python -m allennlp.run predict ./data/qasrl_parser_elmo my_sentences_in.json --include-package nrl --predictor qasrl_parser --output-file my_sentences_out.json
```

**Error**
```
Traceback (most recent call last):
  File "/usr/local/Cellar/python/3.6.5/Frameworks/Python.framework/Versions/3.6/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/local/Cellar/python/3.6.5/Frameworks/Python.framework/Versions/3.6/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Users/fly/Applications/Venvs/py36/lib/python3.6/site-packages/allennlp/run.py", line 18, in <module>
    main(prog="allennlp")
  File "/Users/fly/Applications/Venvs/py36/lib/python3.6/site-packages/allennlp/commands/__init__.py", line 70, in main
    args.func(args)
  File "/Users/fly/Applications/Venvs/py36/lib/python3.6/site-packages/allennlp/commands/predict.py", line 137, in _predict
    predictor = _get_predictor(args)
  File "/Users/fly/Applications/Venvs/py36/lib/python3.6/site-packages/allennlp/commands/predict.py", line 93, in _get_predictor
    overrides=args.overrides)
  File "/Users/fly/Applications/Venvs/py36/lib/python3.6/site-packages/allennlp/models/archival.py", line 154, in load_archive
    cuda_device=cuda_device)
  File "/Users/fly/Applications/Venvs/py36/lib/python3.6/site-packages/allennlp/models/model.py", line 296, in load
    return cls.by_name(model_type)._load(config, serialization_dir, weights_file, cuda_device)
  File "/Users/fly/Applications/Venvs/py36/lib/python3.6/site-packages/allennlp/models/model.py", line 245, in _load
    model.load_state_dict(model_state)
  File "/Users/fly/Applications/Venvs/py36/lib/python3.6/site-packages/torch/nn/modules/module.py", line 721, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for QaSrlParser:
	While copying the parameter named "question_predictor.question_generator.embedder_wh.weight", whose dimensions in the model are torch.Size([2, 100]) and whose dimensions in the checkpoint are torch.Size([8, 100]).
	While copying the parameter named "question_predictor.question_generator.embedder_aux.weight", whose dimensions in the model are torch.Size([2, 100]) and whose dimensions in the checkpoint are torch.Size([22, 100]).
	While copying the parameter named "question_predictor.question_generator.embedder_subj.weight", whose dimensions in the model are torch.Size([2, 100]) and whose dimensions in the checkpoint are torch.Size([3, 100]).
	While copying the parameter named "question_predictor.question_generator.embedder_verb.weight", whose dimensions in the model are torch.Size([2, 100]) and whose dimensions in the checkpoint are torch.Size([19, 100]).
	While copying the parameter named "question_predictor.question_generator.embedder_obj.weight", whose dimensions in the model are torch.Size([2, 100]) and whose dimensions in the checkpoint are torch.Size([3, 100]).
	While copying the parameter named "question_predictor.question_generator.embedder_prep.weight", whose dimensions in the model are torch.Size([2, 100]) and whose dimensions in the checkpoint are torch.Size([187, 100]).
	While copying the parameter named "question_predictor.question_generator.slot_pred_wh.weight", whose dimensions in the model are torch.Size([2, 100]) and whose dimensions in the checkpoint are torch.Size([8, 100]).
	While copying the parameter named "question_predictor.question_generator.slot_pred_wh.bias", whose dimensions in the model are torch.Size([2]) and whose dimensions in the checkpoint are torch.Size([8]).
	While copying the parameter named "question_predictor.question_generator.slot_pred_aux.weight", whose dimensions in the model are torch.Size([2, 100]) and whose dimensions in the checkpoint are torch.Size([22, 100]).
	While copying the parameter named "question_predictor.question_generator.slot_pred_aux.bias", whose dimensions in the model are torch.Size([2]) and whose dimensions in the checkpoint are torch.Size([22]).
	While copying the parameter named "question_predictor.question_generator.slot_pred_subj.weight", whose dimensions in the model are torch.Size([2, 100]) and whose dimensions in the checkpoint are torch.Size([3, 100]).
	While copying the parameter named "question_predictor.question_generator.slot_pred_subj.bias", whose dimensions in the model are torch.Size([2]) and whose dimensions in the checkpoint are torch.Size([3]).
	While copying the parameter named "question_predictor.question_generator.slot_pred_verb.weight", whose dimensions in the model are torch.Size([2, 100]) and whose dimensions in the checkpoint are torch.Size([19, 100]).
	While copying the parameter named "question_predictor.question_generator.slot_pred_verb.bias", whose dimensions in the model are torch.Size([2]) and whose dimensions in the checkpoint are torch.Size([19]).
	While copying the parameter named "question_predictor.question_generator.slot_pred_obj.weight", whose dimensions in the model are torch.Size([2, 100]) and whose dimensions in the checkpoint are torch.Size([3, 100]).
	While copying the parameter named "question_predictor.question_generator.slot_pred_obj.bias", whose dimensions in the model are torch.Size([2]) and whose dimensions in the checkpoint are torch.Size([3]).
	While copying the parameter named "question_predictor.question_generator.slot_pred_prep.weight", whose dimensions in the model are torch.Size([2, 100]) and whose dimensions in the checkpoint are torch.Size([187, 100]).
	While copying the parameter named "question_predictor.question_generator.slot_pred_prep.bias", whose dimensions in the model are torch.Size([2]) and whose dimensions in the checkpoint are torch.Size([187]).
	While copying the parameter named "question_predictor.question_generator.slot_pred_obj2.weight", whose dimensions in the model are torch.Size([2, 100]) and whose dimensions in the checkpoint are torch.Size([6, 100]).
	While copying the parameter named "question_predictor.question_generator.slot_pred_obj2.bias", whose dimensions in the model are torch.Size([2]) and whose dimensions in the checkpoint are torch.Size([6]).
```

Prior to a26e1aa predictions were working fine with minor reshaping of tensors to comply with torch 0.4.0. After a26e1aa,  I suspect the pre-trained model can not be used because of the renaming of weights?

**Comment by nafitzgerald** [comment]
Hi François,

I updated the pretrained model yesterday when I made those changes to the repo. If you redownload it, I believe it should work.

**Comment by lelayf** [comment]
I ran some the same procedure after reverting a26e1aa and the RuntimeError is gone.
I tried to only revert the slot renaming and leave `slot_logits[i][:,:,0:2] -= 9999999` in the forward pass of the question predictor, that produced questions with suspicious syntax (eg: "Where was someone was someone of somewhere?"). If I remove those logit resets the predictions seem much healthier.

**Comment by lelayf** [comment]
@nafitzgerald cool, I _think_ I was working off a fresh download but let me retry this, maybe the GDrive URI changed as well ?

**Comment by lelayf** [comment]
Confirming I am predicting off [the URL found in the README](https://drive.google.com/open?id=1FvMpjTfumVaSfwTOdWbJfEYFgGSAs0CS ) so I suspect the updated archive has a different URL.

**Comment by nafitzgerald** [comment]
Really sorry, I must have just re-uploaded the old version of the archive. I've uploaded the new one now, which I've tested and does work on my end. The URI is the same.

Sorry and thanks for helping me track this down!

**Comment by nafitzgerald** [comment]
Okay, I know what happened. Uploading the new version, it should be up in about 10 minutes -- sorry!

**Comment by nafitzgerald** [comment]
The fixed version is up now. I had accidentally been re-uploading the old archive. Hope this solves the issue!

**Comment by lelayf** [comment]
thank you @nafitzgerald the md5 sum is now different and those runtime errors are gone!
