### ISSUE TITLE
Expanded size of tensor must match existing size

### ISSUE THREAD

**Issue by lelayf** [nafitzgerald/nrl-qasrl#7]
**Environment**

- python 3.6
- allennlp 0.5.1
- torch 0.4.0

**Execution**
```
python -m allennlp.run predict ./data/qasrl_parser_elmo {$INPUT_FILE} --include-package nrl --predictor qasrl_parser --output-file {$OUTPUT_FILE}
```

**Error**
```
2018-06-22 16:40:53,395 - INFO - nrl.service.predictors.qasrl_parser - Reading embeddings from file
Traceback (most recent call last):
  File "/usr/local/Cellar/python/3.6.5/Frameworks/Python.framework/Versions/3.6/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/local/Cellar/python/3.6.5/Frameworks/Python.framework/Versions/3.6/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Users/fly/Applications/Venvs/py36/lib/python3.6/site-packages/allennlp/run.py", line 18, in <module>
    main(prog="allennlp")
  File "/Users/fly/Applications/Venvs/py36/lib/python3.6/site-packages/allennlp/commands/__init__.py", line 70, in main
    args.func(args)
  File "/Users/fly/Applications/Venvs/py36/lib/python3.6/site-packages/allennlp/commands/predict.py", line 155, in _predict
    not args.silent)
  File "/Users/fly/Applications/Venvs/py36/lib/python3.6/site-packages/allennlp/commands/predict.py", line 127, in _run
    _run_predictor(batch_json_data)
  File "/Users/fly/Applications/Venvs/py36/lib/python3.6/site-packages/allennlp/commands/predict.py", line 105, in _run_predictor
    result = predictor.predict_json(batch_data[0])
  File "/Users/fly/nrl-qasrl-lelayf-git/nrl/service/predictors/qasrl_parser.py", line 115, in predict_json
    new_weights[num_words:].copy_(added_weights)
RuntimeError: The expanded size of the tensor (100) must match the existing size (700) at non-singleton dimension 1
```

**Analysis**

I'm curious to hear what version of pytorch this code is based on? With 0.4.0 (which is pulled by allennlp 0.5.1) the tensors need further reshaping. I have a fix ready so if you want your master branch to target 0.4.0 then I can create a PR, other than that I'll have it ready in a new branch in my fork.

**Comment by nafitzgerald** [comment]
Hmm, I'm also running with pytorch 0.4.0 and not getting this issue. This code was written for an older version of pytorch and hastily updated to the newer version in the last few weeks so it's very possible issues like this exist. I wonder why I'm not seeing the error though? Happy to take a look at a PR.

**Comment by lelayf** [comment]
Hmm, so maybe my interpretation of that being linked to torch version is erroneous. This is the [commit](https://github.com/lelayf/nrl-qasrl/commit/2da3d85f5863fc6df324327b3a3fab980b6347ce) I was referring to that is fixing this for me.

**Comment by nafitzgerald** [comment]
Ahh, I see, yeah, I was able to reproduce the issue -- I'll merge your commit. Thanks!

**Comment by nafitzgerald** [comment]
Actually, would you mind submitting a PR and I'll merge it.
